---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 158.160.32.114
      ansible_user: root

vector:
  hosts:
    vector-01:
      ansible_host: 158.160.52.190
      ansible_user: root

lighthouse:
  hosts:
    ligthouse-01:
      ansible_host: 178.154.203.136
      ansible_user: root
