---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 158.160.106.36

vector:
  hosts:
    vector-01:
      ansible_host: 158.160.109.153

lighthouse:
  hosts:
    ligthouse-01:
      ansible_host: 158.160.100.121
